require('dotenv').config();

let ORM = require('../index');

let starter = new ORM({
	dbUrl: process.env.TEST_DB_URL
});

module.exports = starter.pool.query(`
	drop table if exists games cascade;
	drop table if exists teams cascade;
	drop table if exists users cascade;

	create table if not exists teams (
		team_id integer generated by default as identity primary key,
		name text
	);

	create table if not exists users (
		user_id integer generated by default as identity primary key,
		name text,
		team_id integer references teams(team_id),
		created_at timestamp with time zone not null default now()
	);

	create table if not exists games (
		game_id integer generated by default as identity primary key,
		"date" date
	);

	alter table teams add column owner_id integer references users(user_id);

	insert into users (name) values ('Cameron');
	insert into teams (name) values ('Crushinators');
	insert into teams (name) values ('Foobinators');
	insert into teams (name) values ('Barinators');
	insert into teams (name) values ('Bazatrons');
	insert into teams (name) values ('Wildcats');
	insert into teams (name) values ('Banginators');
`);

